In [1]:
import sys

In [2]:
!{sys.executable} -m pip install pandas

Requirement already satisfied: pandas in c:\users\bayzak\appdata\local\programs\python\python313\lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\bayzak\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\bayzak\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\bayzak\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\bayzak\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [16]:
# ex6
import pandas as pd

df = pd.DataFrame({
    "Name": ["Arystan", "Adilet", "Darkhan", "Arsen", "Aizere"],
    "Age": [21, 21, 22, 18, 23],
    "Score": [99, 88, 91, 78, 83]
})

df

      Name  Age  Score
0  Arystan   21     99
1   Adilet   21     88
2  Darkhan   22     91
3    Arsen   18     78
4   Aizere   23     83

In [17]:
# ex7
df.head(3)

      Name  Age  Score
0  Arystan   21     99
1   Adilet   21     88
2  Darkhan   22     91

In [18]:
# ex8
df.describe()

             Age      Score
count   5.000000   5.000000
mean   21.000000  87.800000
std     1.870829   7.981228
min    18.000000  78.000000
25%    21.000000  83.000000
50%    21.000000  88.000000
75%    22.000000  91.000000
max    23.000000  99.000000

In [19]:
# ex9
df["Score"].mean()

np.float64(87.8)

In [20]:
# ex10
df[df["Age"] > 20]

      Name  Age  Score
0  Arystan   21     99
1   Adilet   21     88
2  Darkhan   22     91
4   Aizere   23     83

In [21]:
# ex11
df[df["Score"] > 80]

      Name  Age  Score
0  Arystan   21     99
1   Adilet   21     88
2  Darkhan   22     91
4   Aizere   23     83